version: "3.9"
services:
  risetku-shortener-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: risetku-shortener-client
    ports:
      - 5500:5500
    network_mode: bridge
    restart: unless-stopped
