version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: risetku-api
    env_file:
      - .env
    ports:
      - 5500:5000
    network_mode: bridge
    restart: unless-stopped
